# Generated by Django 3.1.7 on 2021-07-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MapDisplay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_icao', models.CharField(max_length=200)),
                ('aircraft_reg', models.CharField(max_length=200)),
                ('origin_airport', models.CharField(max_length=200)),
                ('destination_airport', models.CharField(max_length=200)),
                ('long', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
