# Generated by Django 3.1.7 on 2021-07-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_display', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapdisplay',
            name='lat',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
