# Generated by Django 3.1.7 on 2021-05-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot_flight_hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_icao', models.CharField(max_length=25)),
                ('takeoff_time', models.DateTimeField()),
                ('landing_time', models.DateTimeField()),
                ('flight_hours', models.DurationField()),
            ],
        ),
    ]
